<p class="section-header">Félicitations</p>
<p class="section-header-caption">Vous venez de créer votre compte</p>
<p class="header"><strong>Un lien d'activation vous a été posté à l'adresse suivante&nbsp;: <?=$this->email ?></strong><br/>
<p class="body"><strong>Vérifiez votre email et cliquez sur le lien d'activation</strong><br/>
<p class="footer">Si vous n'avez pas reçu ce mail dans les quelques minutes, consulter <a href="<?=$this->baseUrl() ?>/content/help-and-support">notre aide</p>