<style>
p.footer {
  margin-left:10px;
  color:#999;
  width:100%;
  text-align:center;
  margin-bottom:2em;
}
</style>
<div class="contentBloc">
  <p class="section-header">Erreur de connection</h2>
  <p class="section-header-caption">&nbsp;</p>
  <p class="fatal-error">
    Ce compte a été bloqué par l'administrateur de votre site, tous vos article et vos commentaires ont été désactivé.
  </p>
  <p class="footer">
    Pour tout question ou réclamation, veuiller consulter la page d'<a href="<?=$this->baseUrl()?>content/help-and-support">aide et support</a>, ou contacter l'administrateur de votre site
  </p>
</div>